# 机器人配置
botConfig:
  triggerKeyword: ""
  blacklist:
    - "公众号名称"
    - "微信名称"

# AI模型配置
modelConfig:
  type: "coze"
  apiKey: "pat_EH60rPVX6Iut2Vt3POtXanHrgqE7tXaGjhVLEeCttpha3XDK9nEcQbu3Io936bWR"
  model: "7455608956103655434"

